/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : RFIDReader
 #	author : Alex
 #	10.08.2017
 #
 # --------------------------------------------------------------------------------*/

#pragma once

enum{
	eCMD_RFID_Plug_Transmit = 1,
	eCMD_RFID_Plug_Disconnect,
	eCMD_RFID_Plug_ReleaseContext,
	eCMD_RFID_Plug_Connect,
	eCMD_RFID_Plug_ListReader,
	eCMD_RFID_Plug_ValidContext,
	eCMD_RFID_Plug_EstablishContext
};


// --- RFIDReader
void RFID_Plug_Transmit( PA_PluginParameters params );
void RFID_Plug_Disconnect( PA_PluginParameters params );
void RFID_Plug_ReleaseContext( PA_PluginParameters params );
void RFID_Plug_Connect( PA_PluginParameters params );
void RFID_Plug_ListReader( PA_PluginParameters params );
void RFID_Plug_ValidContext( PA_PluginParameters params );
void RFID_Plug_EstablishContext( PA_PluginParameters params );
