/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : Empty Project
 #	author : Francois Marchal
 #	01/07/2004
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"
//#include "asiport.h"

void PluginMain( long selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- new theme1

		case 1 :
			new_Command1( params );
			break;

	}
}

// ---------------------------------- new theme1 ----------------------------------


void new_Command1( PA_PluginParameters params )
{
	// --- write the code of new_Command1 here...
//	short a = CurResFile();
	PA_ReturnLong( params, 42 );
}

